# Introduction to NumPy

NumPy (numerical Python) is a very important library in Python for scientific computing and data analysis. Some key aspects of NumPy: [1]

NumPy provides multidimensional array and matrix objects to efficiently store and manipulate large amounts of numerical data. These arrays can hold elements of any numerical type like integers, floats, complex numbers etc.
NumPy arrays are homogenous, meaning all elements must be of the same type. This allows for fast operations on entire arrays instead of element-by-element operations.
NumPy supports N-dimensional arrays, but commonly used are 1D vectors and 2D matrices. Arrays can be easily reshaped and dimensions manipulated.
NumPy contains an extensive library of high-level mathematical functions that can operate on entire arrays rather than single elements. This includes linear algebra, Fourier transforms, random number generation and more.
NumPy integrates well with other Python libraries like SciPy, Pandas, Matplotlib for scientific and data analysis tasks. Arrays can be easily converted to and from standard Python lists.

In [17]:
# install numpy
# pip install numpy


In [18]:
# import the necessary packages 
import pandas as pd
import numpy as np

# What is an Array?

NumPy arrays allow efficient storage and manipulation of large homogeneous data sets. Some key properties of NumPy arrays:

NumPy arrays hold elements of the same data type, unlike standard Python lists which can contain different types. This homogeneity allows for faster operations. [1]
NumPy arrays use N-dimensional grids to represent data, with the number of dimensions specified at array creation time. Common types are 1D vectors and 2D matrices. [2]
Elements in a NumPy array are accessed using integer indices, similar to standard Python lists. But NumPy arrays support fast operations on entire arrays or slices.
NumPy provides many useful methods for working with arrays like reshaping, slicing, sorting, mathematical operations, linear algebra functions and more.
NumPy arrays interact well with other Python code and can be easily converted to and from standard Python lists.


In [19]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [20]:
# 2D arrays
a2 = a[np.newaxis, :]
print(a2)

[[0 1 2 3 4 5]]


In [21]:
a.shape

(6,)

In [22]:
a2.shape

(1, 6)

In [24]:
a2 = a[:,np.newaxis]
print(a2)
a2.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [25]:
a3 = a2[np.newaxis, :]
print(a3)
a3.shape

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]]]


(1, 6, 1)


# Why do we have 1D, 2D & 3D arrays and where we need them ?

NumPy arrays allow representing data in multiple dimensions, with 1D, 2D and 3D being the most common. Here are some examples of where these array types are useful: [1]

1D arrays (vectors) are useful for representing single variables like temperature readings over time or pixel intensities in an image. They are useful anytime you need to store a list of values.
2D arrays (matrices) let you represent image data as pixels organized into rows and columns. They are also useful for storing tabular data like dataframes. 2D arrays are commonly used for linear algebra operations.
3D arrays enable representing volumetric data like those from medical CT/MRI scans or 3D modeling/animation. They allow organizing data into cubes of values indexed by X,Y,Z coordinates.
Higher dimensional arrays beyond 3D also exist but are less common. They may represent multidimensional datasets.

# Creating Arrays with Numpy

In [33]:
a = np.array([1,2,3,4,5,6])
b = np.array([(1, 2, 3, 4, 5, 6), (1, 2, 3, 4, 5, 6)])

In [34]:
a.shape

(6,)

In [36]:
print(b)
b.shape

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


(2, 6)

# initializing arrays

In [38]:
zeros = np.zeros((8,4))  # (rows, columns)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
ones = np.ones((8,4)) # (rows, columns)
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
full = np.full((6,3), 5)
full

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [52]:
# create identity matrix
identity = np.eye(5)   
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
print(a)
print(b)

[1 2 3 4 5 6]
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [54]:
a.dtype

dtype('int32')

In [55]:
b.dtype

dtype('int32')

In [56]:
zeros.dtype

dtype('float64')

In [57]:
ones.dtype

dtype('float64')

In [58]:
full.dtype

dtype('int32')

In [61]:
# data type is changed to float
full = np.full((2,5), 5.5)
full.dtype

dtype('float64')

In [63]:
type(a) # type of array

numpy.ndarray

In [65]:
a.dtype # data type of array elements

dtype('int32')

# array attributes

In [66]:
print(a)

[1 2 3 4 5 6]


In [67]:
a.shape # shape of array elements

(6,)

In [68]:
len(a) # length of array elements

6

In [71]:
a.ndim  # number of dimensions

1

In [72]:
b.ndim # number of dimensions

2

In [73]:
a.size # size of array elements

6

# Basic operations 

In [74]:
g = a - b
g

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [76]:
g = b - a
g

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [78]:
# addidtion of array
h = a + b
h

array([[ 2,  4,  6,  8, 10, 12],
       [ 2,  4,  6,  8, 10, 12]])

In [80]:
# multiply
i = a * b
i

array([[ 1,  4,  9, 16, 25, 36],
       [ 1,  4,  9, 16, 25, 36]])

In [82]:
j = a/b
j

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [84]:
# square root
k = a ** 2
k

array([ 1,  4,  9, 16, 25, 36])