In [2]:
# NumPy 
import numpy as np


In [5]:
empty = np.empty((2, 3))
print(empty)

[[1.20124872e-311 2.56641854e+106 1.20125891e-311]
 [1.20125891e-311 5.43472210e-323 4.94065646e-324]]


In [6]:
print(empty[1])

[1.20125891e-311 5.43472210e-323 4.94065646e-324]


In [8]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [10]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [11]:
# arrays of even numbers
#           start, end, step size
even = np.arange(0, 23, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [12]:
# arrays of odd numbers
odd = np.arange(1, 23, 2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [13]:
# specific difference between numbers
diff = np.arange(0 , 23, .5)
diff

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5])

In [20]:
#              start, end, even space 
lin = np.linspace(0, 20, num=5)
lin

array([ 0.,  5., 10., 15., 20.])

In [24]:
# define the dtype of array
x = np.arange(20, dtype=np.float64)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])