In [2]:
# NumPy 
import numpy as np


In [5]:
empty = np.empty((2, 3))
print(empty)

[[1.20124872e-311 2.56641854e+106 1.20125891e-311]
 [1.20125891e-311 5.43472210e-323 4.94065646e-324]]


In [6]:
print(empty[1])

[1.20125891e-311 5.43472210e-323 4.94065646e-324]


In [8]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [10]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [11]:
# arrays of even numbers
#           start, end, step size
even = np.arange(0, 23, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [12]:
# arrays of odd numbers
odd = np.arange(1, 23, 2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [13]:
# specific difference between numbers
diff = np.arange(0 , 23, .5)
diff

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5])

In [20]:
#              start, end, even space 
lin = np.linspace(0, 20, num=5)
lin

array([ 0.,  5., 10., 15., 20.])

In [24]:
# define the dtype of array
x = np.arange(20, dtype=np.float64)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [25]:
# sorting an array
arr = np.array([2,1,5,3,7,4,6,8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [27]:
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
a = np.array([1,2,3,4,5])
b = np.array([6, 7, 8, 9, 10])

In [30]:
# concatebate these arrays
import numpy as np
c = np.concatenate((a, b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
x = np.array([[1,2], [3,4]])  # 2x2 array
y = np.array([[5, 6]])        # 1x2 array

In [34]:
# concatenate 2D arrays
z = np.concatenate((x, y), axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
w = np.array([[5,7], [8,9]])

In [41]:
y = np.concatenate((x, w) , axis=0)
y

array([[1, 2],
       [3, 4],
       [5, 7],
       [8, 9]])

In [42]:
y = np.concatenate((x, w), axis=1)
y

array([[1, 2, 5, 7],
       [3, 4, 8, 9]])

In [43]:
x.ndim

2

# 3D array

In [61]:
# create a 3D array
import numpy as np
arr3D = np.array([[[1, 2, 3,4], [4, 5, 6,4]], [[7, 8, 9,4], [10, 11, 12,4]],[[7, 8, 9,4], [10, 11, 12,4]]])
arr3D

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  4]],

       [[ 7,  8,  9,  4],
        [10, 11, 12,  4]],

       [[ 7,  8,  9,  4],
        [10, 11, 12,  4]]])

In [62]:
arr3D.size

24

In [63]:
arr3D.ndim

3

In [64]:
arr3D.shape

(3, 2, 4)

In [65]:
# create a 3D array of size (3,1,4)
arra = np.array([[[1, 2, 3, 4]], [[5, 6, 7, 8]], [[9, 10, 11, 12]]])
arra

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [66]:
arra.shape

(3, 1, 4)

In [70]:
# reshape the 3D array into 2D array
arra1 = arra.reshape(6,2)
arra1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [71]:
arra2 = arra1.reshape(2,6)
arra2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

# Indexing and Slicing

In [72]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
a[2]

3

In [74]:
a[2:5]

array([3, 4, 5])

In [76]:
a[-4:]

array([5, 6, 7, 8])

In [77]:
a[-4:-2]

array([5, 6])

In [80]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
b[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [84]:
b[b<5]

array([1, 2, 3, 4])

In [85]:
b[b<=6]

array([1, 2, 3, 4, 5, 6])

In [88]:
# even numbers
b[b % 2 == 0] 

array([ 2,  4,  6,  8, 10, 12])

In [89]:
# odd number
b[b % 2 == 1]  

array([ 1,  3,  5,  7,  9, 11])

In [90]:
# using two conditions
b[(b>2) & (b<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
b[(b>2) | (b<11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])